name: war-in-dockerjboss

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] 
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build with maven
      run: mvn clean package

    - name: Login Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
  
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      id: docker_build
      with: 
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/loginappjboss
